## other configuration excluded from example...
plugins:
  eslint:
    enabled: true
    exclude_patterns:
    - ".eslintrc.json"
exclude_patterns:
- "**/.github/*"
- "**/.vscode/*"
- "**/docs/*"
- "**/specs/*"
- "**/source/tests/*"
- "**/*.json"