name: Lint

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  pull_request:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install modules
      run: yarn
    - name: run ESLint
      run: eslint . --ext .js,.jsx,.ts,.tsx

      
