name: UpdateDocs
on: 
  push:
    branches:
      main
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: install modules
      run: npm install
    - name: Build JSDocs
      run: npx jsdoc -r ./source -d ./docs
    - name: stage changes to docs
      run: git add docs
    - name: Commit files
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git commit -m "Updated Docs [skip actions]"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main